title: Voeg extra kleurvariabelen toe
hero_image: images/banner.png
description: Voeg extra kleurvariabelen toe.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Voeg extra kleurvariabelen toe
